export default {
	login: 'rizalshmbg',
	id: 66808677,
	node_id: 'MDQ6VXNlcjY2ODA4Njc3',
	avatar_url: 'https://avatars.githubusercontent.com/u/66808677?v=4',
	gravatar_id: '',
	url: 'https://api.github.com/users/rizalshmbg',
	html_url: 'https://github.com/rizalshmbg',
	followers_url: 'https://api.github.com/users/rizalshmbg/followers',
	following_url:
		'https://api.github.com/users/rizalshmbg/following{/other_user}',
	gists_url: 'https://api.github.com/users/rizalshmbg/gists{/gist_id}',
	starred_url: 'https://api.github.com/users/rizalshmbg/starred{/owner}{/repo}',
	subscriptions_url: 'https://api.github.com/users/rizalshmbg/subscriptions',
	organizations_url: 'https://api.github.com/users/rizalshmbg/orgs',
	repos_url: 'https://api.github.com/users/rizalshmbg/repos',
	events_url: 'https://api.github.com/users/rizalshmbg/events{/privacy}',
	received_events_url:
		'https://api.github.com/users/rizalshmbg/received_events',
	type: 'User',
	site_admin: false,
	name: 'Rizal Sihombing',
	company: 'Indonesian Computer University',
	blog: '',
	location: 'Bandung, West Java, Indonesia',
	email: null,
	hireable: null,
	bio: 'Jr. Frontend Web Developer',
	twitter_username: 'rizalshmbg',
	public_repos: 42,
	public_gists: 10,
	followers: 22,
	following: 34,
	created_at: '2020-06-12T01:00:43Z',
	updated_at: '2022-10-13T08:27:15Z',
}
