export default [
	{
		login: 'maulana01',
		id: 32027488,
		node_id: 'MDQ6VXNlcjMyMDI3NDg4',
		avatar_url: 'https://avatars.githubusercontent.com/u/32027488?v=4',
		gravatar_id: '',
		url: 'https://api.github.com/users/maulana01',
		html_url: 'https://github.com/maulana01',
		followers_url: 'https://api.github.com/users/maulana01/followers',
		following_url:
			'https://api.github.com/users/maulana01/following{/other_user}',
		gists_url: 'https://api.github.com/users/maulana01/gists{/gist_id}',
		starred_url:
			'https://api.github.com/users/maulana01/starred{/owner}{/repo}',
		subscriptions_url: 'https://api.github.com/users/maulana01/subscriptions',
		organizations_url: 'https://api.github.com/users/maulana01/orgs',
		repos_url: 'https://api.github.com/users/maulana01/repos',
		events_url: 'https://api.github.com/users/maulana01/events{/privacy}',
		received_events_url:
			'https://api.github.com/users/maulana01/received_events',
		type: 'User',
		site_admin: false,
	},
	{
		login: 'Socrad6',
		id: 35413103,
		node_id: 'MDQ6VXNlcjM1NDEzMTAz',
		avatar_url: 'https://avatars.githubusercontent.com/u/35413103?v=4',
		gravatar_id: '',
		url: 'https://api.github.com/users/Socrad6',
		html_url: 'https://github.com/Socrad6',
		followers_url: 'https://api.github.com/users/Socrad6/followers',
		following_url:
			'https://api.github.com/users/Socrad6/following{/other_user}',
		gists_url: 'https://api.github.com/users/Socrad6/gists{/gist_id}',
		starred_url: 'https://api.github.com/users/Socrad6/starred{/owner}{/repo}',
		subscriptions_url: 'https://api.github.com/users/Socrad6/subscriptions',
		organizations_url: 'https://api.github.com/users/Socrad6/orgs',
		repos_url: 'https://api.github.com/users/Socrad6/repos',
		events_url: 'https://api.github.com/users/Socrad6/events{/privacy}',
		received_events_url: 'https://api.github.com/users/Socrad6/received_events',
		type: 'User',
		site_admin: false,
	},
	{
		login: 'mikhlasnr',
		id: 43531715,
		node_id: 'MDQ6VXNlcjQzNTMxNzE1',
		avatar_url: 'https://avatars.githubusercontent.com/u/43531715?v=4',
		gravatar_id: '',
		url: 'https://api.github.com/users/mikhlasnr',
		html_url: 'https://github.com/mikhlasnr',
		followers_url: 'https://api.github.com/users/mikhlasnr/followers',
		following_url:
			'https://api.github.com/users/mikhlasnr/following{/other_user}',
		gists_url: 'https://api.github.com/users/mikhlasnr/gists{/gist_id}',
		starred_url:
			'https://api.github.com/users/mikhlasnr/starred{/owner}{/repo}',
		subscriptions_url: 'https://api.github.com/users/mikhlasnr/subscriptions',
		organizations_url: 'https://api.github.com/users/mikhlasnr/orgs',
		repos_url: 'https://api.github.com/users/mikhlasnr/repos',
		events_url: 'https://api.github.com/users/mikhlasnr/events{/privacy}',
		received_events_url:
			'https://api.github.com/users/mikhlasnr/received_events',
		type: 'User',
		site_admin: false,
	},
	{
		login: 'fauzanjantung',
		id: 44384484,
		node_id: 'MDQ6VXNlcjQ0Mzg0NDg0',
		avatar_url: 'https://avatars.githubusercontent.com/u/44384484?v=4',
		gravatar_id: '',
		url: 'https://api.github.com/users/fauzanjantung',
		html_url: 'https://github.com/fauzanjantung',
		followers_url: 'https://api.github.com/users/fauzanjantung/followers',
		following_url:
			'https://api.github.com/users/fauzanjantung/following{/other_user}',
		gists_url: 'https://api.github.com/users/fauzanjantung/gists{/gist_id}',
		starred_url:
			'https://api.github.com/users/fauzanjantung/starred{/owner}{/repo}',
		subscriptions_url:
			'https://api.github.com/users/fauzanjantung/subscriptions',
		organizations_url: 'https://api.github.com/users/fauzanjantung/orgs',
		repos_url: 'https://api.github.com/users/fauzanjantung/repos',
		events_url: 'https://api.github.com/users/fauzanjantung/events{/privacy}',
		received_events_url:
			'https://api.github.com/users/fauzanjantung/received_events',
		type: 'User',
		site_admin: false,
	},
	{
		login: 'dan-dia',
		id: 57033160,
		node_id: 'MDQ6VXNlcjU3MDMzMTYw',
		avatar_url: 'https://avatars.githubusercontent.com/u/57033160?v=4',
		gravatar_id: '',
		url: 'https://api.github.com/users/dan-dia',
		html_url: 'https://github.com/dan-dia',
		followers_url: 'https://api.github.com/users/dan-dia/followers',
		following_url:
			'https://api.github.com/users/dan-dia/following{/other_user}',
		gists_url: 'https://api.github.com/users/dan-dia/gists{/gist_id}',
		starred_url: 'https://api.github.com/users/dan-dia/starred{/owner}{/repo}',
		subscriptions_url: 'https://api.github.com/users/dan-dia/subscriptions',
		organizations_url: 'https://api.github.com/users/dan-dia/orgs',
		repos_url: 'https://api.github.com/users/dan-dia/repos',
		events_url: 'https://api.github.com/users/dan-dia/events{/privacy}',
		received_events_url: 'https://api.github.com/users/dan-dia/received_events',
		type: 'User',
		site_admin: false,
	},
	{
		login: 'ilhamzaki',
		id: 57041786,
		node_id: 'MDQ6VXNlcjU3MDQxNzg2',
		avatar_url: 'https://avatars.githubusercontent.com/u/57041786?v=4',
		gravatar_id: '',
		url: 'https://api.github.com/users/ilhamzaki',
		html_url: 'https://github.com/ilhamzaki',
		followers_url: 'https://api.github.com/users/ilhamzaki/followers',
		following_url:
			'https://api.github.com/users/ilhamzaki/following{/other_user}',
		gists_url: 'https://api.github.com/users/ilhamzaki/gists{/gist_id}',
		starred_url:
			'https://api.github.com/users/ilhamzaki/starred{/owner}{/repo}',
		subscriptions_url: 'https://api.github.com/users/ilhamzaki/subscriptions',
		organizations_url: 'https://api.github.com/users/ilhamzaki/orgs',
		repos_url: 'https://api.github.com/users/ilhamzaki/repos',
		events_url: 'https://api.github.com/users/ilhamzaki/events{/privacy}',
		received_events_url:
			'https://api.github.com/users/ilhamzaki/received_events',
		type: 'User',
		site_admin: false,
	},
	{
		login: 'farelarden',
		id: 58240454,
		node_id: 'MDQ6VXNlcjU4MjQwNDU0',
		avatar_url: 'https://avatars.githubusercontent.com/u/58240454?v=4',
		gravatar_id: '',
		url: 'https://api.github.com/users/farelarden',
		html_url: 'https://github.com/farelarden',
		followers_url: 'https://api.github.com/users/farelarden/followers',
		following_url:
			'https://api.github.com/users/farelarden/following{/other_user}',
		gists_url: 'https://api.github.com/users/farelarden/gists{/gist_id}',
		starred_url:
			'https://api.github.com/users/farelarden/starred{/owner}{/repo}',
		subscriptions_url: 'https://api.github.com/users/farelarden/subscriptions',
		organizations_url: 'https://api.github.com/users/farelarden/orgs',
		repos_url: 'https://api.github.com/users/farelarden/repos',
		events_url: 'https://api.github.com/users/farelarden/events{/privacy}',
		received_events_url:
			'https://api.github.com/users/farelarden/received_events',
		type: 'User',
		site_admin: false,
	},
	{
		login: 'onedayxzn',
		id: 59074406,
		node_id: 'MDQ6VXNlcjU5MDc0NDA2',
		avatar_url: 'https://avatars.githubusercontent.com/u/59074406?v=4',
		gravatar_id: '',
		url: 'https://api.github.com/users/onedayxzn',
		html_url: 'https://github.com/onedayxzn',
		followers_url: 'https://api.github.com/users/onedayxzn/followers',
		following_url:
			'https://api.github.com/users/onedayxzn/following{/other_user}',
		gists_url: 'https://api.github.com/users/onedayxzn/gists{/gist_id}',
		starred_url:
			'https://api.github.com/users/onedayxzn/starred{/owner}{/repo}',
		subscriptions_url: 'https://api.github.com/users/onedayxzn/subscriptions',
		organizations_url: 'https://api.github.com/users/onedayxzn/orgs',
		repos_url: 'https://api.github.com/users/onedayxzn/repos',
		events_url: 'https://api.github.com/users/onedayxzn/events{/privacy}',
		received_events_url:
			'https://api.github.com/users/onedayxzn/received_events',
		type: 'User',
		site_admin: false,
	},
	{
		login: 'MancungXYZ',
		id: 60146927,
		node_id: 'MDQ6VXNlcjYwMTQ2OTI3',
		avatar_url: 'https://avatars.githubusercontent.com/u/60146927?v=4',
		gravatar_id: '',
		url: 'https://api.github.com/users/MancungXYZ',
		html_url: 'https://github.com/MancungXYZ',
		followers_url: 'https://api.github.com/users/MancungXYZ/followers',
		following_url:
			'https://api.github.com/users/MancungXYZ/following{/other_user}',
		gists_url: 'https://api.github.com/users/MancungXYZ/gists{/gist_id}',
		starred_url:
			'https://api.github.com/users/MancungXYZ/starred{/owner}{/repo}',
		subscriptions_url: 'https://api.github.com/users/MancungXYZ/subscriptions',
		organizations_url: 'https://api.github.com/users/MancungXYZ/orgs',
		repos_url: 'https://api.github.com/users/MancungXYZ/repos',
		events_url: 'https://api.github.com/users/MancungXYZ/events{/privacy}',
		received_events_url:
			'https://api.github.com/users/MancungXYZ/received_events',
		type: 'User',
		site_admin: false,
	},
	{
		login: 'stepanusjanu19',
		id: 62204530,
		node_id: 'MDQ6VXNlcjYyMjA0NTMw',
		avatar_url: 'https://avatars.githubusercontent.com/u/62204530?v=4',
		gravatar_id: '',
		url: 'https://api.github.com/users/stepanusjanu19',
		html_url: 'https://github.com/stepanusjanu19',
		followers_url: 'https://api.github.com/users/stepanusjanu19/followers',
		following_url:
			'https://api.github.com/users/stepanusjanu19/following{/other_user}',
		gists_url: 'https://api.github.com/users/stepanusjanu19/gists{/gist_id}',
		starred_url:
			'https://api.github.com/users/stepanusjanu19/starred{/owner}{/repo}',
		subscriptions_url:
			'https://api.github.com/users/stepanusjanu19/subscriptions',
		organizations_url: 'https://api.github.com/users/stepanusjanu19/orgs',
		repos_url: 'https://api.github.com/users/stepanusjanu19/repos',
		events_url: 'https://api.github.com/users/stepanusjanu19/events{/privacy}',
		received_events_url:
			'https://api.github.com/users/stepanusjanu19/received_events',
		type: 'User',
		site_admin: false,
	},
	{
		login: 'tian2301',
		id: 66317793,
		node_id: 'MDQ6VXNlcjY2MzE3Nzkz',
		avatar_url: 'https://avatars.githubusercontent.com/u/66317793?v=4',
		gravatar_id: '',
		url: 'https://api.github.com/users/tian2301',
		html_url: 'https://github.com/tian2301',
		followers_url: 'https://api.github.com/users/tian2301/followers',
		following_url:
			'https://api.github.com/users/tian2301/following{/other_user}',
		gists_url: 'https://api.github.com/users/tian2301/gists{/gist_id}',
		starred_url: 'https://api.github.com/users/tian2301/starred{/owner}{/repo}',
		subscriptions_url: 'https://api.github.com/users/tian2301/subscriptions',
		organizations_url: 'https://api.github.com/users/tian2301/orgs',
		repos_url: 'https://api.github.com/users/tian2301/repos',
		events_url: 'https://api.github.com/users/tian2301/events{/privacy}',
		received_events_url:
			'https://api.github.com/users/tian2301/received_events',
		type: 'User',
		site_admin: false,
	},
	{
		login: 'erwintobing15',
		id: 70240402,
		node_id: 'MDQ6VXNlcjcwMjQwNDAy',
		avatar_url: 'https://avatars.githubusercontent.com/u/70240402?v=4',
		gravatar_id: '',
		url: 'https://api.github.com/users/erwintobing15',
		html_url: 'https://github.com/erwintobing15',
		followers_url: 'https://api.github.com/users/erwintobing15/followers',
		following_url:
			'https://api.github.com/users/erwintobing15/following{/other_user}',
		gists_url: 'https://api.github.com/users/erwintobing15/gists{/gist_id}',
		starred_url:
			'https://api.github.com/users/erwintobing15/starred{/owner}{/repo}',
		subscriptions_url:
			'https://api.github.com/users/erwintobing15/subscriptions',
		organizations_url: 'https://api.github.com/users/erwintobing15/orgs',
		repos_url: 'https://api.github.com/users/erwintobing15/repos',
		events_url: 'https://api.github.com/users/erwintobing15/events{/privacy}',
		received_events_url:
			'https://api.github.com/users/erwintobing15/received_events',
		type: 'User',
		site_admin: false,
	},
	{
		login: 'RACHMAN21',
		id: 72843070,
		node_id: 'MDQ6VXNlcjcyODQzMDcw',
		avatar_url: 'https://avatars.githubusercontent.com/u/72843070?v=4',
		gravatar_id: '',
		url: 'https://api.github.com/users/RACHMAN21',
		html_url: 'https://github.com/RACHMAN21',
		followers_url: 'https://api.github.com/users/RACHMAN21/followers',
		following_url:
			'https://api.github.com/users/RACHMAN21/following{/other_user}',
		gists_url: 'https://api.github.com/users/RACHMAN21/gists{/gist_id}',
		starred_url:
			'https://api.github.com/users/RACHMAN21/starred{/owner}{/repo}',
		subscriptions_url: 'https://api.github.com/users/RACHMAN21/subscriptions',
		organizations_url: 'https://api.github.com/users/RACHMAN21/orgs',
		repos_url: 'https://api.github.com/users/RACHMAN21/repos',
		events_url: 'https://api.github.com/users/RACHMAN21/events{/privacy}',
		received_events_url:
			'https://api.github.com/users/RACHMAN21/received_events',
		type: 'User',
		site_admin: false,
	},
	{
		login: 'fi-yona',
		id: 72845037,
		node_id: 'MDQ6VXNlcjcyODQ1MDM3',
		avatar_url: 'https://avatars.githubusercontent.com/u/72845037?v=4',
		gravatar_id: '',
		url: 'https://api.github.com/users/fi-yona',
		html_url: 'https://github.com/fi-yona',
		followers_url: 'https://api.github.com/users/fi-yona/followers',
		following_url:
			'https://api.github.com/users/fi-yona/following{/other_user}',
		gists_url: 'https://api.github.com/users/fi-yona/gists{/gist_id}',
		starred_url: 'https://api.github.com/users/fi-yona/starred{/owner}{/repo}',
		subscriptions_url: 'https://api.github.com/users/fi-yona/subscriptions',
		organizations_url: 'https://api.github.com/users/fi-yona/orgs',
		repos_url: 'https://api.github.com/users/fi-yona/repos',
		events_url: 'https://api.github.com/users/fi-yona/events{/privacy}',
		received_events_url: 'https://api.github.com/users/fi-yona/received_events',
		type: 'User',
		site_admin: false,
	},
	{
		login: 'argyaa',
		id: 72845615,
		node_id: 'MDQ6VXNlcjcyODQ1NjE1',
		avatar_url: 'https://avatars.githubusercontent.com/u/72845615?v=4',
		gravatar_id: '',
		url: 'https://api.github.com/users/argyaa',
		html_url: 'https://github.com/argyaa',
		followers_url: 'https://api.github.com/users/argyaa/followers',
		following_url: 'https://api.github.com/users/argyaa/following{/other_user}',
		gists_url: 'https://api.github.com/users/argyaa/gists{/gist_id}',
		starred_url: 'https://api.github.com/users/argyaa/starred{/owner}{/repo}',
		subscriptions_url: 'https://api.github.com/users/argyaa/subscriptions',
		organizations_url: 'https://api.github.com/users/argyaa/orgs',
		repos_url: 'https://api.github.com/users/argyaa/repos',
		events_url: 'https://api.github.com/users/argyaa/events{/privacy}',
		received_events_url: 'https://api.github.com/users/argyaa/received_events',
		type: 'User',
		site_admin: false,
	},
	{
		login: 'RendyDermawan10119030',
		id: 72881555,
		node_id: 'MDQ6VXNlcjcyODgxNTU1',
		avatar_url: 'https://avatars.githubusercontent.com/u/72881555?v=4',
		gravatar_id: '',
		url: 'https://api.github.com/users/RendyDermawan10119030',
		html_url: 'https://github.com/RendyDermawan10119030',
		followers_url:
			'https://api.github.com/users/RendyDermawan10119030/followers',
		following_url:
			'https://api.github.com/users/RendyDermawan10119030/following{/other_user}',
		gists_url:
			'https://api.github.com/users/RendyDermawan10119030/gists{/gist_id}',
		starred_url:
			'https://api.github.com/users/RendyDermawan10119030/starred{/owner}{/repo}',
		subscriptions_url:
			'https://api.github.com/users/RendyDermawan10119030/subscriptions',
		organizations_url:
			'https://api.github.com/users/RendyDermawan10119030/orgs',
		repos_url: 'https://api.github.com/users/RendyDermawan10119030/repos',
		events_url:
			'https://api.github.com/users/RendyDermawan10119030/events{/privacy}',
		received_events_url:
			'https://api.github.com/users/RendyDermawan10119030/received_events',
		type: 'User',
		site_admin: false,
	},
	{
		login: 'hayinananta',
		id: 72958200,
		node_id: 'MDQ6VXNlcjcyOTU4MjAw',
		avatar_url: 'https://avatars.githubusercontent.com/u/72958200?v=4',
		gravatar_id: '',
		url: 'https://api.github.com/users/hayinananta',
		html_url: 'https://github.com/hayinananta',
		followers_url: 'https://api.github.com/users/hayinananta/followers',
		following_url:
			'https://api.github.com/users/hayinananta/following{/other_user}',
		gists_url: 'https://api.github.com/users/hayinananta/gists{/gist_id}',
		starred_url:
			'https://api.github.com/users/hayinananta/starred{/owner}{/repo}',
		subscriptions_url: 'https://api.github.com/users/hayinananta/subscriptions',
		organizations_url: 'https://api.github.com/users/hayinananta/orgs',
		repos_url: 'https://api.github.com/users/hayinananta/repos',
		events_url: 'https://api.github.com/users/hayinananta/events{/privacy}',
		received_events_url:
			'https://api.github.com/users/hayinananta/received_events',
		type: 'User',
		site_admin: false,
	},
	{
		login: 'todayisvin',
		id: 73047637,
		node_id: 'MDQ6VXNlcjczMDQ3NjM3',
		avatar_url: 'https://avatars.githubusercontent.com/u/73047637?v=4',
		gravatar_id: '',
		url: 'https://api.github.com/users/todayisvin',
		html_url: 'https://github.com/todayisvin',
		followers_url: 'https://api.github.com/users/todayisvin/followers',
		following_url:
			'https://api.github.com/users/todayisvin/following{/other_user}',
		gists_url: 'https://api.github.com/users/todayisvin/gists{/gist_id}',
		starred_url:
			'https://api.github.com/users/todayisvin/starred{/owner}{/repo}',
		subscriptions_url: 'https://api.github.com/users/todayisvin/subscriptions',
		organizations_url: 'https://api.github.com/users/todayisvin/orgs',
		repos_url: 'https://api.github.com/users/todayisvin/repos',
		events_url: 'https://api.github.com/users/todayisvin/events{/privacy}',
		received_events_url:
			'https://api.github.com/users/todayisvin/received_events',
		type: 'User',
		site_admin: false,
	},
	{
		login: 'rxzl18',
		id: 83757728,
		node_id: 'MDQ6VXNlcjgzNzU3NzI4',
		avatar_url: 'https://avatars.githubusercontent.com/u/83757728?v=4',
		gravatar_id: '',
		url: 'https://api.github.com/users/rxzl18',
		html_url: 'https://github.com/rxzl18',
		followers_url: 'https://api.github.com/users/rxzl18/followers',
		following_url: 'https://api.github.com/users/rxzl18/following{/other_user}',
		gists_url: 'https://api.github.com/users/rxzl18/gists{/gist_id}',
		starred_url: 'https://api.github.com/users/rxzl18/starred{/owner}{/repo}',
		subscriptions_url: 'https://api.github.com/users/rxzl18/subscriptions',
		organizations_url: 'https://api.github.com/users/rxzl18/orgs',
		repos_url: 'https://api.github.com/users/rxzl18/repos',
		events_url: 'https://api.github.com/users/rxzl18/events{/privacy}',
		received_events_url: 'https://api.github.com/users/rxzl18/received_events',
		type: 'User',
		site_admin: false,
	},
	{
		login: 'ARusDian',
		id: 87649208,
		node_id: 'MDQ6VXNlcjg3NjQ5MjA4',
		avatar_url: 'https://avatars.githubusercontent.com/u/87649208?v=4',
		gravatar_id: '',
		url: 'https://api.github.com/users/ARusDian',
		html_url: 'https://github.com/ARusDian',
		followers_url: 'https://api.github.com/users/ARusDian/followers',
		following_url:
			'https://api.github.com/users/ARusDian/following{/other_user}',
		gists_url: 'https://api.github.com/users/ARusDian/gists{/gist_id}',
		starred_url: 'https://api.github.com/users/ARusDian/starred{/owner}{/repo}',
		subscriptions_url: 'https://api.github.com/users/ARusDian/subscriptions',
		organizations_url: 'https://api.github.com/users/ARusDian/orgs',
		repos_url: 'https://api.github.com/users/ARusDian/repos',
		events_url: 'https://api.github.com/users/ARusDian/events{/privacy}',
		received_events_url:
			'https://api.github.com/users/ARusDian/received_events',
		type: 'User',
		site_admin: false,
	},
	{
		login: 'hendrawijayasubandi',
		id: 96402737,
		node_id: 'U_kgDOBb79MQ',
		avatar_url: 'https://avatars.githubusercontent.com/u/96402737?v=4',
		gravatar_id: '',
		url: 'https://api.github.com/users/hendrawijayasubandi',
		html_url: 'https://github.com/hendrawijayasubandi',
		followers_url: 'https://api.github.com/users/hendrawijayasubandi/followers',
		following_url:
			'https://api.github.com/users/hendrawijayasubandi/following{/other_user}',
		gists_url:
			'https://api.github.com/users/hendrawijayasubandi/gists{/gist_id}',
		starred_url:
			'https://api.github.com/users/hendrawijayasubandi/starred{/owner}{/repo}',
		subscriptions_url:
			'https://api.github.com/users/hendrawijayasubandi/subscriptions',
		organizations_url: 'https://api.github.com/users/hendrawijayasubandi/orgs',
		repos_url: 'https://api.github.com/users/hendrawijayasubandi/repos',
		events_url:
			'https://api.github.com/users/hendrawijayasubandi/events{/privacy}',
		received_events_url:
			'https://api.github.com/users/hendrawijayasubandi/received_events',
		type: 'User',
		site_admin: false,
	},
	{
		login: 'Davidalehandro34',
		id: 106859641,
		node_id: 'U_kgDOBl6MeQ',
		avatar_url: 'https://avatars.githubusercontent.com/u/106859641?v=4',
		gravatar_id: '',
		url: 'https://api.github.com/users/Davidalehandro34',
		html_url: 'https://github.com/Davidalehandro34',
		followers_url: 'https://api.github.com/users/Davidalehandro34/followers',
		following_url:
			'https://api.github.com/users/Davidalehandro34/following{/other_user}',
		gists_url: 'https://api.github.com/users/Davidalehandro34/gists{/gist_id}',
		starred_url:
			'https://api.github.com/users/Davidalehandro34/starred{/owner}{/repo}',
		subscriptions_url:
			'https://api.github.com/users/Davidalehandro34/subscriptions',
		organizations_url: 'https://api.github.com/users/Davidalehandro34/orgs',
		repos_url: 'https://api.github.com/users/Davidalehandro34/repos',
		events_url:
			'https://api.github.com/users/Davidalehandro34/events{/privacy}',
		received_events_url:
			'https://api.github.com/users/Davidalehandro34/received_events',
		type: 'User',
		site_admin: false,
	},
]
